# Generated by Django 5.0.6 on 2024-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_connectionmodel_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
