# Generated by Django 5.0.6 on 2024-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_alter_connectionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionmodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
